name: setup-node-pnpm

description: Setup node and pnpm
runs:
  using: "composite"
  steps:
    - name: Install pnpm package manager
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

    - name: Set global store
      shell: bash
      run: pnpm config set store-dir ~/.pnpm-store

    - name: Setup Node.js environment
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version-file: ".nvmrc"
        # cache: "pnpm"
        # package-manager-cache: false
        registry-url: 'https://npm.pkg.github.com'
        scope: '@acocia-agaps'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Add bin directory to PATH
      shell: bash
      run: pnpm bin >> $GITHUB_PATH
